server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/ecom-application/config-repo
          default-label: master